name: 'CLA Signature Bot'
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/master')) }}

jobs:
  CLABot:
    if: github.event_name == 'pull_request_target' || startsWith(github.event.comment.html_url, '/pull/') || github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/cla') && github.actor != 'dependabot[bot]' && (contains(github
